import {
  StyleSheet,
  Platform,
} from "react-native";
import { COLORS } from "./ProfileColors";
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 16 : 4,
    paddingBottom: 8,
  },
  headerTitle: { fontWeight: "900", color: COLORS.ink },
  editIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },

  profileCard: {
    marginHorizontal: 20,
    marginTop: 10,
    backgroundColor: COLORS.white,
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: "center",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  avatarWrap: { width: 80, height: 80, marginBottom: 12 },
  avatarImage: { width: 80, height: 80, borderRadius: 40, backgroundColor: "#F7F5FF" },
  avatarPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.lavender,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: { color: COLORS.white, fontWeight: "900" },
  avatarBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.pink,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  name: { fontWeight: "900", color: COLORS.ink },
  email: { fontWeight: "600", color: COLORS.inkLight, marginTop: 2 },
  phone: { fontWeight: "600", color: COLORS.inkLight, marginTop: 1 },

  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 18,
    width: "100%",
  },
  statItem: { flex: 1, alignItems: "center" },
  statValue: { fontSize: 16, fontWeight: "900", color: COLORS.ink },
  statLabel: { fontSize: 11, fontWeight: "600", color: COLORS.inkLight, marginTop: 2 },
  statDivider: { width: 1, height: 28, backgroundColor: "#F0EAFB" },

  sectionTitle: {
    fontWeight: "800",
    color: COLORS.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginHorizontal: 24,
    marginTop: 22,
    marginBottom: 8,
  },
  menuCard: {
    marginHorizontal: 20,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  menuRowBorder: { borderBottomWidth: 1, borderBottomColor: "#F5F2FC" },
  menuIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  menuLabel: { flex: 1, fontSize: 14, fontWeight: "700", color: COLORS.ink },
  menuLabelDanger: { color: "#E4574A" },

  versionText: {
    textAlign: "center",
    color: "#C9C0E8",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 24,
  },

  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: COLORS.white,
    paddingTop: 10,
    paddingBottom: Platform.OS === "ios" ? 24 : 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 10,
  },
  tabItem: { flex: 1, alignItems: "center", gap: 3 },
  tabLabel: { fontSize: 10.5, color: COLORS.inkLight, fontWeight: "700" },
  tabLabelActive: { color: COLORS.pink },
});