import {  StyleSheet, Platform,} from 'react-native'
import {COLORS} from '../HomePage/Colors';
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 16 : 4,
    paddingBottom: 8,
  },
  greetingSmall: { color: COLORS.inkLight, fontWeight: "600" },
  greetingName: { color: COLORS.ink, fontWeight: "900" },
  headerIcons: { flexDirection: "row", gap: 10 },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },
  cartBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: COLORS.pink,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  cartBadgeText: { color: COLORS.white, fontSize: 9, fontWeight: "800" },

  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    marginTop: 10,
    borderRadius: 18,
    paddingHorizontal: 14,
    height: 50,
    gap: 8,
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  searchInput: { flex: 1, color: COLORS.ink, fontWeight: "600", fontSize: 14 },
  filterBtn: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: COLORS.lavender,
    alignItems: "center",
    justifyContent: "center",
  },

  banner: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginTop: 18,
    borderRadius: 24,
    padding: 20,
    overflow: "hidden",
  },
  bannerTitle: { color: COLORS.white, fontWeight: "900" },
  bannerSubtitle: { color: "rgba(255,255,255,0.85)", fontWeight: "600", marginTop: 2 },
  bannerBtn: {
    backgroundColor: COLORS.white,
    alignSelf: "flex-start",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 12,
  },
  bannerBtnText: { color: COLORS.pink, fontWeight: "800", fontSize: 12.5 },

  sectionTitle: { color: COLORS.ink, fontWeight: "900", marginHorizontal: 20, marginTop: 22, marginBottom: 10 },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginRight: 20,
  },
  seeAll: { color: COLORS.pink, fontWeight: "700", fontSize: 12.5 },

  categoryRow: { paddingHorizontal: 20, gap: 10, paddingBottom: 4 },
  categoryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#EDE7FA",
  },
  categoryChipActive: {
    backgroundColor: COLORS.pink,
    borderColor: COLORS.pink,
  },
  categoryLabel: { color: COLORS.ink, fontWeight: "700", fontSize: 12.5 },
  categoryLabelActive: { color: COLORS.white },

  flavorCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 3,
  },
  flavorImageWrap: {
    height: 110,
    alignItems: "center",
    justifyContent: "center",
  },
  favBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
  },
  flavorInfo: { padding: 10 },
  flavorName: { color: COLORS.ink, fontWeight: "800" },
  ratingRow: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 3 },
  ratingText: { color: COLORS.inkLight, fontWeight: "700", fontSize: 11 },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  priceText: { color: COLORS.pink, fontWeight: "900" },
  addBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.mint,
    alignItems: "center",
    justifyContent: "center",
  },

  emptyText: {
    textAlign: "center",
    color: COLORS.inkLight,
    fontWeight: "600",
    marginTop: 30,
    paddingHorizontal: 20,
  },

  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: COLORS.white,
    paddingTop: 10,
    paddingBottom: Platform.OS === "ios" ? 24 : 12,
    
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 10,
  },
  tabItem: { flex: 1, alignItems: "center", gap: 3 },
  tabLabel: { fontSize: 10.5, color: COLORS.inkLight, fontWeight: "700" },
  tabLabelActive: { color: COLORS.pink },
});