"""
generate_vocabulary.py
======================
Builds src/middleware/notification/vocabulary.ts from the training CSV, so the
middleware only ever sends the model field values it actually saw in training.

Run from the project root whenever the dataset changes:

    python scripts/generate_vocabulary.py all.csv src/middleware/notification/vocabulary.ts
"""
import json
import re
import sys

import pandas as pd

# A value must appear at least this many times in the CSV to count as "seen
# enough in training". Drops one-off typos like "Cart Recovery." (1 row).
MIN_COUNT = {
    "scenario": 20, "user_activity": 20,
    "category": 5, "customer_type": 5, "time_of_day": 5, "day_type": 5,
    "season": 5, "weather": 5, "urgency": 5, "tone": 5,
}
DISCOUNT_MIN_COUNT = 5


def main(csv_path: str, out_path: str) -> None:
    df = pd.read_csv(csv_path, engine="python", on_bad_lines="skip", encoding="utf-8-sig").fillna("")

    vocab = {}
    for field, min_count in MIN_COUNT.items():
        counts = df[field].astype(str).str.strip().value_counts()  # most frequent first
        vocab[field] = [v for v, c in counts.items() if v and c >= min_count]

    # Numeric discounts ("15%") are accepted by pattern in the normalizer, so only
    # the non-numeric labels ("Free Delivery", "Buy1Get1", ...) go in the list.
    counts = df["discount"].astype(str).str.strip().value_counts()
    vocab["discount"] = [
        v for v, c in counts.items()
        if v and c >= DISCOUNT_MIN_COUNT and not re.fullmatch(r"\d+%", v)
    ]

    lines = [
        "// AUTO-GENERATED by scripts/generate_vocabulary.py from the training CSV.",
        "// Do not edit by hand - re-run the script when the dataset changes.",
        "",
        "export const VOCABULARY = {",
    ]
    for field, values in vocab.items():
        lines.append(f"  {field}: {json.dumps(values, ensure_ascii=False)},")
    lines += ["} as const;", "", "export type VocabularyField = keyof typeof VOCABULARY;", ""]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    for field, values in vocab.items():
        print(f"{field:14s} {len(values):4d} values")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
