import {

  StyleSheet,

  Platform,
 
} from "react-native";
import { COLORS } from "./ProductColors";
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },

  imageWrap: {
    width: "100%",
    height: 320,
    backgroundColor: "#FFF3D6",
  },
  image: { width: "100%", height: "100%" },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  backBtn: {
    position: "absolute",
    top: Platform.OS === "android" ? 16 : 10,
    left: 16,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
  },
  favBtn: {
    position: "absolute",
    top: Platform.OS === "android" ? 16 : 10,
    right: 16,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
  },
  discountBadge: {
    position: "absolute",
    bottom: 16,
    left: 16,
    backgroundColor: COLORS.pink,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
  },
  discountBadgeText: { color: COLORS.white, fontWeight: "900", fontSize: 12 },

  detailsCard: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -24,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 10,
  },
  titleRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  categoryChip: {
    alignSelf: "flex-start",
    backgroundColor: "#F3F0FF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    marginBottom: 6,
  },
  categoryChipText: { color: COLORS.lavender, fontWeight: "800", fontSize: 11 },
  name: { fontWeight: "900", color: COLORS.ink },

  stockBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, flexShrink: 0 },
  stockBadgeIn: { backgroundColor: "#E8FAF0" },
  stockBadgeOut: { backgroundColor: "#FFF0F0" },
  stockText: { fontSize: 11, fontWeight: "800" },
  stockTextIn: { color: "#2E9E5B" },
  stockTextOut: { color: "#E4574A" },

  priceRow: { flexDirection: "row", alignItems: "baseline", gap: 10, marginTop: 14 },
  price: { fontWeight: "900", color: COLORS.pink },
  originalPrice: {
    color: COLORS.inkLight,
    fontWeight: "700",
    textDecorationLine: "line-through",
  },

  sectionLabel: {
    fontWeight: "800",
    color: COLORS.ink,
    marginTop: 20,
    marginBottom: 8,
  },
  description: { color: COLORS.inkLight, fontWeight: "500", lineHeight: 20 },

  qtyRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  qtyBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F7F5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyValue: { fontWeight: "900", color: COLORS.ink, minWidth: 20, textAlign: "center" },
  stockHint: { color: COLORS.inkLight, fontWeight: "600", marginLeft: "auto" },

  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.white,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: Platform.OS === "ios" ? 28 : 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
  },
  bottomTotalWrap: { marginRight: 2 },
  bottomLabel: { color: COLORS.inkLight, fontWeight: "700", fontSize: 10.5 },
  bottomTotal: { color: COLORS.ink, fontWeight: "900" },

  addToCartBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#FFE1EC",
    paddingVertical: 13,
    borderRadius: 24,
  },
  addToCartText: { color: COLORS.pink, fontWeight: "900" },

  btnDisabled: { backgroundColor: "#EDE7FA", shadowOpacity: 0 },
});