import {
  StyleSheet,
  Platform,
} from "react-native";
import { COLORS } from "./CartColors";
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 16 : 4,
    paddingBottom: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  headerTitle: { fontWeight: "900", color: COLORS.ink },
  clearText: { color: "#E4574A", fontWeight: "700", fontSize: 13 },

  emptyWrap: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 30 },
  emptyTitle: { fontWeight: "900", color: COLORS.ink, marginTop: 12 },
  emptySubtitle: { color: COLORS.inkLight, fontWeight: "600", marginTop: 4, textAlign: "center" },
  emptyBtn: {
    marginTop: 20,
    backgroundColor: COLORS.pink,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
  },
  emptyBtnText: { color: COLORS.white, fontWeight: "800", fontSize: 14 },

  itemsWrap: { paddingHorizontal: 20, gap: 12, marginTop: 6 },
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 10,
    gap: 12,
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  itemImage: {
    width: 58,
    height: 58,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  itemInfo: { flex: 1 },
  itemName: { fontWeight: "800", color: COLORS.ink },
  itemPrice: { fontWeight: "700", color: COLORS.pink, marginTop: 2 },
  qtyRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 8 },
  qtyBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#F7F5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyText: { fontWeight: "800", color: COLORS.ink, fontSize: 13, minWidth: 16, textAlign: "center" },
  removeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFF0F0",
    alignItems: "center",
    justifyContent: "center",
  },

  promoWrap: { flexDirection: "row", gap: 10, paddingHorizontal: 20, marginTop: 18 },
  promoInputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 46,
  },
  promoInput: { flex: 1, color: COLORS.ink, fontWeight: "700", fontSize: 13 },
  promoBtn: {
    backgroundColor: COLORS.lavender,
    paddingHorizontal: 18,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  promoBtnText: { color: COLORS.white, fontWeight: "800", fontSize: 13 },
  promoError: { color: "#E4574A", fontSize: 11.5, fontWeight: "700", marginTop: 6, marginLeft: 22 },
  promoSuccess: { color: "#2E9E5B", fontSize: 11.5, fontWeight: "700", marginTop: 6, marginLeft: 22 },

  summaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 20,
    marginTop: 18,
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryTitle: { fontWeight: "900", color: COLORS.ink, marginBottom: 10 },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  summaryLabel: { color: COLORS.inkLight, fontWeight: "600", fontSize: 13 },
  summaryValue: { color: COLORS.ink, fontWeight: "700", fontSize: 13 },
  summaryDivider: { height: 1, backgroundColor: "#F0EAFB", marginVertical: 6 },
  totalLabel: { color: COLORS.ink, fontWeight: "900", fontSize: 15 },
  totalValue: { color: COLORS.pink, fontWeight: "900", fontSize: 17 },

  checkoutBar: {
    position: "absolute",
    bottom: 50,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.white,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: Platform.OS === "ios" ? 28 : 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
  },
  checkoutLabel: { color: COLORS.inkLight, fontWeight: "700", fontSize: 11 },
  checkoutTotal: { color: COLORS.ink, fontWeight: "900" },
  checkoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.pink,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 26,
    shadowColor: COLORS.pink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  checkoutBtnText: { color: COLORS.white, fontWeight: "900" },
});
