import {
  StyleSheet,
  Platform,
} from "react-native";
import { COLORS } from "./ConfirmOrderColors";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 16 : 4,
    paddingBottom: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  headerTitle: { fontWeight: "900", color: COLORS.ink },

  centerWrap: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 30 },
  emptyTitle: { fontWeight: "900", color: COLORS.ink, fontSize: 17, marginTop: 12 },
  emptySubtitle: { color: COLORS.inkLight, fontWeight: "600", fontSize: 13, marginTop: 4, textAlign: "center" },

  sectionTitle: {
    fontWeight: "900",
    color: COLORS.ink,
    fontSize: 14,
    marginHorizontal: 20,
    marginTop: 18,
    marginBottom: 8,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 14,
    marginHorizontal: 20,
    shadowColor: "#B388FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },

  addressInputCard: { flexDirection: "row", alignItems: "flex-start", gap: 10, minHeight: 90 },
  addressInput: {
    flex: 1,
    minHeight: 64,
    color: COLORS.ink,
    fontWeight: "600",
    fontSize: 14,
    padding: 0,
  },
  inputError: { borderWidth: 1.5, borderColor: "#FFB4B4" },
  errorText: { color: "#E4574A", fontSize: 11.5, fontWeight: "700", marginTop: 6, marginHorizontal: 24 },

  orderItemRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 10 },
  rowBorder: { borderBottomWidth: 1, borderBottomColor: "#F5F2FC" },
  orderItemEmoji: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#FFF3D6",
    alignItems: "center",
    justifyContent: "center",
  },
  orderItemName: { fontWeight: "800", color: COLORS.ink, fontSize: 13.5 },
  orderItemSub: { fontWeight: "600", color: COLORS.inkLight, fontSize: 12, marginTop: 2 },
  orderItemTotal: { fontWeight: "900", color: COLORS.pink, fontSize: 14 },

  summaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  summaryLabel: { color: COLORS.inkLight, fontWeight: "600", fontSize: 13 },
  summaryValue: { color: COLORS.ink, fontWeight: "700", fontSize: 13 },
  summaryDivider: { height: 1, backgroundColor: "#F0EAFB", marginVertical: 6 },
  totalLabel: { color: COLORS.ink, fontWeight: "900", fontSize: 15 },
  totalValue: { color: COLORS.pink, fontWeight: "900", fontSize: 17 },
  noteText: { color: COLORS.inkLight, fontSize: 11.5, fontWeight: "600", lineHeight: 16, marginTop: 2 },

  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.white,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: Platform.OS === "ios" ? 28 : 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
  },
  bottomLabel: { color: COLORS.inkLight, fontWeight: "700", fontSize: 11 },
  bottomTotal: { color: COLORS.ink, fontWeight: "900" },
  placeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minWidth: 150,
    backgroundColor: COLORS.pink,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 26,
    shadowColor: COLORS.pink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  placeBtnText: { color: COLORS.white, fontWeight: "900" },

  /* success phase */
  successTop: { alignItems: "center", paddingTop: 30, paddingHorizontal: 30, paddingBottom: 6 },
  successCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: COLORS.mint,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.mint,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 14,
    elevation: 6,
  },
  successTitle: { fontWeight: "900", color: COLORS.ink, marginTop: 16 },
  successSubtitle: {
    color: COLORS.inkLight,
    fontWeight: "600",
    marginTop: 6,
    textAlign: "center",
    lineHeight: 19,
  },

  metaRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 6 },
  metaLabel: { color: COLORS.inkLight, fontWeight: "600", fontSize: 13 },
  metaValue: { color: COLORS.ink, fontWeight: "800", fontSize: 13 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  badgeText: { fontSize: 11, fontWeight: "800" },

  addressRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  addressText: { flex: 1, color: COLORS.ink, fontWeight: "600", fontSize: 13.5, lineHeight: 19 },

  successActions: { paddingHorizontal: 20, marginTop: 22, gap: 10 },
  primaryBtn: {
    backgroundColor: COLORS.pink,
    paddingVertical: 14,
    borderRadius: 26,
    alignItems: "center",
    shadowColor: COLORS.pink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  primaryBtnText: { color: COLORS.white, fontWeight: "900", fontSize: 15 },
  secondaryBtn: {
    backgroundColor: "#FFE1EC",
    paddingVertical: 14,
    borderRadius: 26,
    alignItems: "center",
  },
  secondaryBtnText: { color: COLORS.pink, fontWeight: "900", fontSize: 15 },
});
